name:                parties-backend
version:             0.1.0.0
github:              "githubuser/parties-backend"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/parties-backend#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant
- servant-server
- wai
- warp
- mtl
- either
- bytestring
- persistent
- persistent-postgresql
- text
- monad-logger
- servant-auth
- servant-auth-server
- password
- esqueleto
- jose
- containers
- random
- http-conduit
- lens
- unordered-containers
- aeson-typescript
- time
- directory
- wai-app-static



library:
  source-dirs: src

executables:
  parties-backend-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base
    - parties-backend
    when:
    - condition: false
      other-modules: Paths_parties_backend
  ts-def:
    main: Main.hs
    source-dirs: tsdef
    dependencies:
    - base
    - parties-backend
    when:
    - condition: false
      other-modules: Paths_parties_backend

tests:
  parties-backend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - parties-backend
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
