name: build-and-deploy-app
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: event-app
      PROJECT_ID: eventti
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v2
    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/374308934121/locations/global/workloadIdentityPools/gh-pool/providers/my-provider'
        service_account: 'github-actions@eventti.iam.gserviceaccount.com'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - run: gcloud iam service-accounts list
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - run: |
        gcloud auth configure-docker -q
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ollimandoliini/parties:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Build
      run: |-
        docker push eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
