name: build-and-deploy-app
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: event-app
      PROJECT_ID: eventti
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v2
    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/374308934121/locations/global/workloadIdentityPools/gh-pool/providers/my-provider'
        service_account: 'github-actions@eventti.iam.gserviceaccount.com'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Configure Google Docker Container Registry
      run: |
        gcloud auth configure-docker -q
    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: |
          ollimandoliini/parties:latest
          eu.gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Push Docker Image
      run: |-
        docker push eu.gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Apply Infrastructure
      run: |-
        cd infra/environments/dev
        terraform init
        terraform plan -var 'image_tag=${{ github.sha }}'
        terraform apply -auto-approve -var 'image_tag=${{ github.sha }}'
